#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="quanlilophoc")]
	public partial class databaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsinhvien(sinhvien instance);
    partial void Updatesinhvien(sinhvien instance);
    partial void Deletesinhvien(sinhvien instance);
    partial void Insertlophoc(lophoc instance);
    partial void Updatelophoc(lophoc instance);
    partial void Deletelophoc(lophoc instance);
    #endregion
		
		public databaseDataContext() : 
				base(global::loginApp.Properties.Settings.Default.quanlilophocConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<sinhvien> sinhviens
		{
			get
			{
				return this.GetTable<sinhvien>();
			}
		}
		
		public System.Data.Linq.Table<lophoc> lophocs
		{
			get
			{
				return this.GetTable<lophoc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sinhvien")]
	public partial class sinhvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _studentID;
		
		private string _studentName;
		
		private System.Nullable<bool> _gender;
		
		private System.Nullable<System.DateTime> _bthDay;
		
		private System.Nullable<int> _classID;
		
		private string _studentCode;
		
		private EntityRef<lophoc> _lophoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstudentIDChanging(int value);
    partial void OnstudentIDChanged();
    partial void OnstudentNameChanging(string value);
    partial void OnstudentNameChanged();
    partial void OngenderChanging(System.Nullable<bool> value);
    partial void OngenderChanged();
    partial void OnbthDayChanging(System.Nullable<System.DateTime> value);
    partial void OnbthDayChanged();
    partial void OnclassIDChanging(System.Nullable<int> value);
    partial void OnclassIDChanged();
    partial void OnstudentCodeChanging(string value);
    partial void OnstudentCodeChanged();
    #endregion
		
		public sinhvien()
		{
			this._lophoc = default(EntityRef<lophoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					this.OnstudentIDChanging(value);
					this.SendPropertyChanging();
					this._studentID = value;
					this.SendPropertyChanged("studentID");
					this.OnstudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentName", DbType="NVarChar(100)")]
		public string studentName
		{
			get
			{
				return this._studentName;
			}
			set
			{
				if ((this._studentName != value))
				{
					this.OnstudentNameChanging(value);
					this.SendPropertyChanging();
					this._studentName = value;
					this.SendPropertyChanged("studentName");
					this.OnstudentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Bit")]
		public System.Nullable<bool> gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bthDay", DbType="DateTime")]
		public System.Nullable<System.DateTime> bthDay
		{
			get
			{
				return this._bthDay;
			}
			set
			{
				if ((this._bthDay != value))
				{
					this.OnbthDayChanging(value);
					this.SendPropertyChanging();
					this._bthDay = value;
					this.SendPropertyChanged("bthDay");
					this.OnbthDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classID", DbType="Int")]
		public System.Nullable<int> classID
		{
			get
			{
				return this._classID;
			}
			set
			{
				if ((this._classID != value))
				{
					if (this._lophoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnclassIDChanging(value);
					this.SendPropertyChanging();
					this._classID = value;
					this.SendPropertyChanged("classID");
					this.OnclassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentCode", DbType="VarChar(100)")]
		public string studentCode
		{
			get
			{
				return this._studentCode;
			}
			set
			{
				if ((this._studentCode != value))
				{
					this.OnstudentCodeChanging(value);
					this.SendPropertyChanging();
					this._studentCode = value;
					this.SendPropertyChanged("studentCode");
					this.OnstudentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lophoc_sinhvien", Storage="_lophoc", ThisKey="classID", OtherKey="classID", IsForeignKey=true)]
		public lophoc lophoc
		{
			get
			{
				return this._lophoc.Entity;
			}
			set
			{
				lophoc previousValue = this._lophoc.Entity;
				if (((previousValue != value) 
							|| (this._lophoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._lophoc.Entity = null;
						previousValue.sinhviens.Remove(this);
					}
					this._lophoc.Entity = value;
					if ((value != null))
					{
						value.sinhviens.Add(this);
						this._classID = value.classID;
					}
					else
					{
						this._classID = default(Nullable<int>);
					}
					this.SendPropertyChanged("lophoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lophoc")]
	public partial class lophoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _classID;
		
		private string _className;
		
		private System.Nullable<System.DateTime> _createAt;
		
		private string _classCode;
		
		private EntitySet<sinhvien> _sinhviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnclassIDChanging(int value);
    partial void OnclassIDChanged();
    partial void OnclassNameChanging(string value);
    partial void OnclassNameChanged();
    partial void OncreateAtChanging(System.Nullable<System.DateTime> value);
    partial void OncreateAtChanged();
    partial void OnclassCodeChanging(string value);
    partial void OnclassCodeChanged();
    #endregion
		
		public lophoc()
		{
			this._sinhviens = new EntitySet<sinhvien>(new Action<sinhvien>(this.attach_sinhviens), new Action<sinhvien>(this.detach_sinhviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int classID
		{
			get
			{
				return this._classID;
			}
			set
			{
				if ((this._classID != value))
				{
					this.OnclassIDChanging(value);
					this.SendPropertyChanging();
					this._classID = value;
					this.SendPropertyChanged("classID");
					this.OnclassIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_className", DbType="NVarChar(50)")]
		public string className
		{
			get
			{
				return this._className;
			}
			set
			{
				if ((this._className != value))
				{
					this.OnclassNameChanging(value);
					this.SendPropertyChanging();
					this._className = value;
					this.SendPropertyChanged("className");
					this.OnclassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> createAt
		{
			get
			{
				return this._createAt;
			}
			set
			{
				if ((this._createAt != value))
				{
					this.OncreateAtChanging(value);
					this.SendPropertyChanging();
					this._createAt = value;
					this.SendPropertyChanged("createAt");
					this.OncreateAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classCode", DbType="VarChar(100)")]
		public string classCode
		{
			get
			{
				return this._classCode;
			}
			set
			{
				if ((this._classCode != value))
				{
					this.OnclassCodeChanging(value);
					this.SendPropertyChanging();
					this._classCode = value;
					this.SendPropertyChanged("classCode");
					this.OnclassCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lophoc_sinhvien", Storage="_sinhviens", ThisKey="classID", OtherKey="classID")]
		public EntitySet<sinhvien> sinhviens
		{
			get
			{
				return this._sinhviens;
			}
			set
			{
				this._sinhviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sinhviens(sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.lophoc = this;
		}
		
		private void detach_sinhviens(sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.lophoc = null;
		}
	}
}
#pragma warning restore 1591
